// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Hand

package main

// HandSlice is a slice of type Hand. Use it where you would use []Hand.
type HandSlice []Hand

// Where returns a new HandSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv HandSlice) Where(fn func(Hand) bool) (result HandSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
